sudo: required
services:
    - docker

script:
    - docker build -t michelecava/node .
    - docker images michelecava/nodes

before_deploy:
    - docker login -u michelecava -p Hannspee123?

deploy:
    provider: script
    script: docker push michelecava/node
    on:
        branch: master
    